# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "lightstep.collector.SpanContext" do
    optional :trace_id, :uint64, 1
    optional :span_id, :uint64, 2
    map :baggage, :string, :string, 3
  end
  add_message "lightstep.collector.KeyValue" do
    optional :key, :string, 1
    oneof :value do
      optional :string_value, :string, 2
      optional :int_value, :int64, 3
      optional :double_value, :double, 4
      optional :bool_value, :bool, 5
      optional :json_value, :string, 6
    end
  end
  add_message "lightstep.collector.Log" do
    optional :timestamp, :message, 1, "google.protobuf.Timestamp"
    repeated :fields, :message, 2, "lightstep.collector.KeyValue"
  end
  add_message "lightstep.collector.Reference" do
    optional :relationship, :enum, 1, "lightstep.collector.Reference.Relationship"
    optional :span_context, :message, 2, "lightstep.collector.SpanContext"
  end
  add_enum "lightstep.collector.Reference.Relationship" do
    value :CHILD_OF, 0
    value :FOLLOWS_FROM, 1
  end
  add_message "lightstep.collector.Span" do
    optional :span_context, :message, 1, "lightstep.collector.SpanContext"
    optional :operation_name, :string, 2
    repeated :references, :message, 3, "lightstep.collector.Reference"
    optional :start_timestamp, :message, 4, "google.protobuf.Timestamp"
    optional :duration_micros, :uint64, 5
    repeated :tags, :message, 6, "lightstep.collector.KeyValue"
    repeated :logs, :message, 7, "lightstep.collector.Log"
  end
  add_message "lightstep.collector.Reporter" do
    optional :reporter_id, :uint64, 1
    repeated :tags, :message, 4, "lightstep.collector.KeyValue"
  end
  add_message "lightstep.collector.MetricsSample" do
    optional :name, :string, 1
    oneof :value do
      optional :int_value, :int64, 2
      optional :double_value, :double, 3
    end
  end
  add_message "lightstep.collector.InternalMetrics" do
    optional :start_timestamp, :message, 1, "google.protobuf.Timestamp"
    optional :duration_micros, :uint64, 2
    repeated :logs, :message, 3, "lightstep.collector.Log"
    repeated :counts, :message, 4, "lightstep.collector.MetricsSample"
    repeated :gauges, :message, 5, "lightstep.collector.MetricsSample"
  end
  add_message "lightstep.collector.Auth" do
    optional :access_token, :string, 1
  end
  add_message "lightstep.collector.ReportRequest" do
    optional :reporter, :message, 1, "lightstep.collector.Reporter"
    optional :auth, :message, 2, "lightstep.collector.Auth"
    repeated :spans, :message, 3, "lightstep.collector.Span"
    optional :timestamp_offset_micros, :int64, 5
    optional :internal_metrics, :message, 6, "lightstep.collector.InternalMetrics"
  end
  add_message "lightstep.collector.Command" do
    optional :disable, :bool, 1
  end
  add_message "lightstep.collector.ReportResponse" do
    repeated :commands, :message, 1, "lightstep.collector.Command"
    optional :receive_timestamp, :message, 2, "google.protobuf.Timestamp"
    optional :transmit_timestamp, :message, 3, "google.protobuf.Timestamp"
    repeated :errors, :string, 4
    repeated :warnings, :string, 5
    repeated :infos, :string, 6
  end
end

module Lightstep
  module Collector
    SpanContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.SpanContext").msgclass
    KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.KeyValue").msgclass
    Log = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Log").msgclass
    Reference = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Reference").msgclass
    Reference::Relationship = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Reference.Relationship").enummodule
    Span = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Span").msgclass
    Reporter = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Reporter").msgclass
    MetricsSample = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.MetricsSample").msgclass
    InternalMetrics = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.InternalMetrics").msgclass
    Auth = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Auth").msgclass
    ReportRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.ReportRequest").msgclass
    Command = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.Command").msgclass
    ReportResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightstep.collector.ReportResponse").msgclass
  end
end
