version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ .Branch }}-
            - gem-cache-v1-
      - run: bundle
      - save_cache:
          paths:
            - /usr/local/bundle
          key: gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test

